name: Build and push Docker image to Artifact Registry

on:
  push:
    branches:
      - main
    paths-ignore:
      - "aws/**"
      - "*.env.template"
      - "README.md"

env:
  GO111MODULE: on
  REGION: asia-northeast1
  # See the output values of github.com/Kitsuya0828/resource-label-checker-terraform/gcp/shared
  WORKLOAD_IDENTITY_PROVIDER_NAME: projects/1091668953261/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider
  IMAGE_NAME: asia-northeast1-docker.pkg.dev/resource-label-checker-shared/resource-label-checker/resource-label-checker
  SERVICE_ACCOUNT_EMAIL: github-actions@resource-label-checker-shared.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{env.WORKLOAD_IDENTITY_PROVIDER_NAME}}
          service_account: ${{env.SERVICE_ACCOUNT_EMAIL}}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{env.REGION}}.pkg.dev

      - name: Build a docker image
        run: docker build -t ${{env.IMAGE_NAME}} -f gcp/Dockerfile .

      - name: Push the docker image
        run: docker push ${{env.IMAGE_NAME}}
